source "https://rubygems.org"

gem "sinatra"
gem "rack-flash3"
gem "rerun"
gem "activerecord"
gem "gschool_database_connection"
gem "rspec"
gem "database_cleaner"
gem "capybara"
gem "rake"
gem "pg", "~> 0.17.1"
